### ISSUE TITLE
feature:

### ISSUE THREAD

**Issue by romannikov** [amaanq/tree-sitter-starlark#6]
### Did you check the tree-sitter docs?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

-

### Additional context

Adding code-lens commands to run BAZEL commands

Bazel has runnable rules, like:
```
go_binary(
    name = "main",
    embed = [":main_lib"],
    visibility = ["//visibility:public"],
)
```
and buildable, like:
```
go_library(
    name = "main_lib",
    srcs = ["main.go"],
    deps = [
    ],
    visibility = ["//visibility:private"],
)
```
Currently the extension doesn't have code lens commands to run/build these rules. Is it possible to add them?

**Comment by amaanq** [comment]
this is a parser not an lsp.
